---

- name: install required packages
  apt: pkg={{ item }}
       state=present
       update_cache=yes
       install_recommends=no
  with_items:
    - git
    - curl
    - make
  tags:
    - install

- name: checkout plenv from github
  git: repo={{ plenv.repo_url }}
       dest={{ plenv.install_path }}
       version={{ plenv.repo_version | default("HEAD") }}
       accept_hostkey=yes
  tags:
    - install

- name: get minimum perl-build from github
  get_url: url={{ item.url }}
           dest={{ plenv.install_path}}/bin
           force=yes
  with_items: plenv.perlbuild_files
  tags:
    - install

- name: set permissions for perl-build files
  file: path={{ plenv.install_path }}/bin/{{ item.name }}
        mode=0755
  with_items: plenv.perlbuild_files
  tags:
    - install

- name: add plenv initialization to profile
  template: src=plenv.sh.j2
            dest=/etc/profile.d/plenv.sh
            owner=root
            group=root
            mode=0755
  tags:
    - install
