- name: install perl
  plenv: user="{{ item.0.name }}" perl="{{ item.1 }}"
  with_subelements:
    - plenv_user
    - perls
  tags:
    - user

- name: set global perl
  plenv: user="{{ item.name }}" global="{{ item.global }}"
  with_items: plenv_user
  tags:
    - user
