- name: create plugins directory (user)
  file: path=~{{ item.name }}/.plenv/plugins
        state=directory
        owner={{ item.name }}
        group={{ item.group }}
  with_items: plenv_user
  sudo: true
  when: plenv_user
  tags:
    - user
    - plugin

- name: install plugins (user)
  git: repo={{ item.1.repo }}
       dest={{ item.0.name }}/.plenv/plugins/{{ item.1.name }}
       version={{ item.1.version | default('HEAD') }}
  with_together:
    - plenv_user
    - plugins
  sudo: true
  when: plenv_user and item.1.plugins
  tags:
    - user
    - plugin

#- name: install perl (system)
#  shell: bash -lc "plenv install {{ item }}"
#  sudo: yes
#  with_items: plenv_system.perls
#  register: perl_install
#  when: plenv_system.perls
#  failed_when: perl_install.rc not in [0,255]
#  changed_when: perl_install.rc == 0
#  tags:
#    - system
#    - install
#
#- name: check global perl version (system)
#  shell: bash -lc "plenv version | cut -d ' ' -f 1"
#  sudo: yes
#  register: check_perl_global
#  when: plenv_system.global
#  changed_when: not check_perl_global.stdout
#  tags:
#    - system
#    - global
#
#- name: set global perl version (system) 
#  shell: bash -lc "plenv global {{ plenv_system.global }}"
#  sudo: yes
#  register: set_perl_global
#  when: plenv_system.global
#  changed_when: set_perl_global.rc == 0 and check_perl_global.stdout != plenv_system.global
#  tags:
#    - system
#    - global
